### PR TITLE
Bump to 0.9.2

### PR DESCRIPTION
**Pull request by kwilcox**
https://django-polymorphic.readthedocs.io/en/latest/changelog.html#version-0-9-2-2016-05-04

### CODE REVIEW

**Comment by kwilcox** [comment]
Waited 12 days for the travis build... will send another PR.

**Comment by ocefpaf** [comment]
Ouch! did you try to cancel and re-start?

**Comment by kwilcox** [comment]
Not sure how to do that, just sent another PR

**Comment by ocefpaf** [comment]
Just a close and re-open should do.

**Pull request closed without merging**
