### PR TITLE
Bump to 0.9.2 and regen smithy

### PR DESCRIPTION
**Pull request by kwilcox**
https://github.com/chrisglass/django_polymorphic/blob/master/docs/changelog.rst#version-092-2016-05-04

### CODE REVIEW

**Comment by kwilcox** [comment]
These pypi URL change are really a pain.

**Comment by ocefpaf** [comment]
> These pypi URL change are really a pain.

After ions of URL re-directing to make user life easy PyPA decides that we should suffer as if the internet was just invented.

**Comment by kwilcox** [comment]
`0.9.2` didn't get a .tar.gz uploaded to pypi. I'll raise an issue in the source repo.

**Comment by ocefpaf** [comment]
Or just go straight to the source:

```
fn: django_polymorphic-{{ version }}.tar.gz
url: https://github.com/chrisglass/django_polymorphic/archive/v{{ version }}.tar.gz
sha256: 069c38da2450850d5cf68dea4f520b18373dc607a97939ea2cdef357c62365b8
```

**Pull request closed without merging**
